### ISSUE TITLE
Build the core features

### ISSUE THREAD

**Issue by NADOOITChristophBa** [NADOOITChristophBa/ContactNetwork#10]
## Issue Type
- [ ] Feature: Core Features Development

## Issue Description
Start developing the most essential features such as contact tracking, email importation, and processing.

## Tasks
- [ ] Develop contact tracking feature.
- [ ] Develop email importation feature.
- [ ] Develop email processing feature.
