### ISSUE TITLE
Test your code

### ISSUE THREAD

**Issue by NADOOITChristophBa** [NADOOITChristophBa/ContactNetwork#11]
## Issue Type
- [ ] Feature: Code Testing

## Issue Description
Implement tests for the features developed to ensure they are working as expected.

## Tasks
- [ ] Write tests for contact tracking feature.
- [ ] Write tests for email importation feature.
- [ ] Write tests for email processing feature.
