### ISSUE TITLE
Iterate on your project

### ISSUE THREAD

**Issue by NADOOITChristophBa** [NADOOITChristophBa/ContactNetwork#12]
## Issue Type
- [ ] Feature: Project Iteration

## Issue Description
Based on feedback and testing, iterate over the project making necessary changes and improvements.

## Tasks
- [ ] Gather feedback on project.
- [ ] Perform testing and identify areas for improvement.
- [ ] Implement changes and improvements.
