### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by NADOOITChristophBa** [NADOOITChristophBa/ContactNetwork#13]
## Issue Type
- [ ] Feature: Documentation

## Issue Description
Document all the features of the application and how to use them.

## Tasks
- [ ] Document the contact tracking feature.
- [ ] Document the email importation feature.
- [ ] Document the email processing feature.
