### ISSUE TITLE
Deployment

### ISSUE THREAD

**Issue by NADOOITChristophBa** [NADOOITChristophBa/ContactNetwork#14]
## Issue Type
- [ ] Feature: Deployment

## Issue Description
When satisfied with the application, consider how to distribute it.

## Tasks
- [ ] Decide on the distribution method for the application.
- [ ] Prepare the application for deployment.
- [ ] Deploy the application.
