### ISSUE TITLE
Define the project structure

### ISSUE THREAD

**Issue by NADOOITChristophBa** [NADOOITChristophBa/ContactNetwork#8]
## Issue Type
- [ ] Feature: Project Structure

## Issue Description
Define the folder structure for the project, where to place the source code, tests, documentation, etc.

## Tasks
- [ ] Create a root folder for the source code.
- [ ] Create a separate folder for tests.
- [ ] Create a documentation folder.

**Comment by NADOOITChristophBa** [comment]
Ah, I see. Let's work on the "Project Structure" issue then. 

Here's a general Python project structure to follow:

1. **Create a root folder for the source code.** The name of this folder will typically be the name of your project.

    ```
    ContactNetwork
    ```

2. **Within this root folder, create a separate folder for your Python source code.** This folder will house the main Python files for your project. For clarity, we can call it `src`:

    ```
    ContactNetwork
    └── src
    ```

3. **Create a separate folder for tests.** This is where you'll place all your test cases. Typically, this is called `tests`:

    ```
    ContactNetwork
    ├── src
    └── tests
    ```

4. **Create a documentation folder.** This is where all your project's documentation will live. It's commonly named `docs`:

    ```
    ContactNetwork
    ├── src
    ├── tests
    └── docs
    ```

You can create these directories using the command line. If you're on a Unix-based system (like Linux or MacOS), you can use the `mkdir` command to create directories. If you're on Windows, you can use the `md` command. Here's how you can create these directories in one line:

For Unix-based systems:

```bash
mkdir ContactNetwork ContactNetwork/src ContactNetwork/tests ContactNetwork/docs
```

For Windows:

```cmd
md ContactNetwork\src ContactNetwork\tests ContactNetwork\docs
```

After running this command, your project structure should be in place.

This structure is just a starting point. As your project grows, you might want to add other directories like `data` (for data files), `config` (for configuration files), or `utils` (for utility scripts). Feel free to adjust this structure as needed for your project's specific requirements.
