### ISSUE TITLE
Decide on the tech stack

### ISSUE THREAD

**Issue by NADOOITChristophBa** [NADOOITChristophBa/ContactNetwork#9]
## Issue Type
- [ ] Feature: Tech Stack Setup

## Issue Description
Setup a Python development environment and acquire API keys for OpenAI's GPT-3.

## Tasks
- [ ] Set up a virtual environment for the project.
- [ ] Install necessary Python packages.
- [ ] Acquire API keys for GPT-3.
